# Vectors

In [2]:
import torch

## Creating vectors

In [66]:
a = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
print(a)
print(a.shape)

tensor([1., 2., 3., 4.])
torch.Size([4])


In [4]:
print(torch.zeros(10))
print(torch.ones(10))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [23]:
torch.rand(10000)

tensor([0.4801, 0.1123, 0.7066,  ..., 0.5916, 0.4651, 0.8932])

## Vector operations

In [63]:
a.sum()

tensor(10.)

In [69]:
print(a.sum().shape)
print(a.sum().item())

torch.Size([])
10.0


In [58]:
b = torch.tensor([10, 11, 12, 13], dtype=torch.float32)
print(b)

tensor([10., 11., 12., 13.])


In [29]:
a + b

tensor([11., 13., 15., 17.])

In [30]:
a * b

tensor([10., 22., 36., 52.])

In [31]:
a ** 2

tensor([ 1.,  4.,  9., 16.])

In [32]:
a.sqrt()

tensor([1.0000, 1.4142, 1.7321, 2.0000])

In [33]:
a.log()

tensor([0.0000, 0.6931, 1.0986, 1.3863])

In [34]:
torch.cat([a, b])

tensor([ 1.,  2.,  3.,  4., 10., 11., 12., 13.])

In [62]:
a.dot(b)

tensor(120.)

In [36]:
a + 17

tensor([18., 19., 20., 21.])

# Matrices

In [48]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(A)
print(A.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [53]:
B = torch.rand([3, 4])
print(B)

tensor([[0.1459, 0.0552, 0.0483, 0.4052],
        [0.4719, 0.5244, 0.6610, 0.5729],
        [0.1657, 0.3133, 0.7074, 0.3744]])


In [54]:
B @ a  # matrix-vector multiplication

tensor([2.0218, 5.7952, 4.4120])

In [55]:
A @ B  # matrix-matrix multiplication

tensor([[1.5869, 2.0438, 3.4925, 2.6741],
        [3.9376, 4.7224, 7.7425, 6.7314]])

In [70]:
B.sum(dim=1)

tensor([0.6546, 2.2301, 1.5608])

In [74]:
B.mean(dim=0)

tensor([0.2612, 0.2976, 0.4722, 0.4508])

# 3D tensors

In [76]:
X = torch.tensor([
    [[1,2], [3,4]],
    [[5,6], [7,8]],
    [[9,10], [11,12]]], dtype=torch.float32)
print(X)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [78]:
X @ A

tensor([[[  9.,  12.,  15.],
         [ 19.,  26.,  33.]],

        [[ 29.,  40.,  51.],
         [ 39.,  54.,  69.]],

        [[ 49.,  68.,  87.],
         [ 59.,  82., 105.]]])