# Intro to pytorch Tensors

In [1]:
import torch

## Creating vectors

In [2]:
a = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
print(a)
print(a.shape)

tensor([1., 2., 3., 4.])
torch.Size([4])


In [3]:
print(torch.zeros(10))
print(torch.ones(10))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [4]:
torch.rand(10000)

tensor([0.6127, 0.8965, 0.7534,  ..., 0.2553, 0.3943, 0.1487])

## Vector operations

In [5]:
a.sum()

tensor(10.)

In [6]:
print(a.sum().shape)
print(a.sum().item())

torch.Size([])
10.0


In [7]:
b = torch.tensor([10, 11, 12, 13], dtype=torch.float32)
print(b)

tensor([10., 11., 12., 13.])


In [8]:
a + b

tensor([11., 13., 15., 17.])

In [9]:
a * b

tensor([10., 22., 36., 52.])

In [10]:
a ** 2

tensor([ 1.,  4.,  9., 16.])

In [11]:
a.sqrt()

tensor([1.0000, 1.4142, 1.7321, 2.0000])

In [12]:
a.log()

tensor([0.0000, 0.6931, 1.0986, 1.3863])

In [13]:
torch.cat([a, b])

tensor([ 1.,  2.,  3.,  4., 10., 11., 12., 13.])

In [14]:
a.dot(b)

tensor(120.)

In [15]:
a + 17

tensor([18., 19., 20., 21.])

In [25]:
a.argmax(0)

tensor(3)

## Matrices

In [17]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(A)
print(A.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [18]:
B = torch.rand([3, 4])
print(B)

tensor([[0.3621, 0.2942, 0.1394, 0.6673],
        [0.9018, 0.0154, 0.8717, 0.1557],
        [0.5143, 0.5293, 0.0756, 0.4765]])


In [19]:
B @ a  # matrix-vector multiplication

tensor([4.0377, 4.1704, 3.7058])

In [20]:
A @ B  # matrix-matrix multiplication

tensor([[3.7086, 1.9129, 2.1095, 2.4082],
        [9.0431, 4.4296, 5.3695, 6.3066]])

In [21]:
B.sum(dim=1)

tensor([1.4629, 1.9446, 1.5957])

In [22]:
B.mean(dim=0)

tensor([0.5927, 0.2796, 0.3622, 0.4332])

In [26]:
A.reshape(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

## 3D tensors

In [23]:
X = torch.tensor([
    [[1,2], [3,4]],
    [[5,6], [7,8]],
    [[9,10], [11,12]]], dtype=torch.float32)
print(X)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [24]:
X @ A

tensor([[[  9.,  12.,  15.],
         [ 19.,  26.,  33.]],

        [[ 29.,  40.,  51.],
         [ 39.,  54.,  69.]],

        [[ 49.,  68.,  87.],
         [ 59.,  82., 105.]]])